# Generated by Django 3.1.1 on 2020-09-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bingo1', models.ImageField(null=True, upload_to='bingo')),
                ('bingo2', models.ImageField(null=True, upload_to='bingo')),
                ('bingo3', models.ImageField(null=True, upload_to='bingo')),
                ('bingo4', models.ImageField(null=True, upload_to='bingo')),
                ('bingo5', models.ImageField(null=True, upload_to='bingo')),
                ('bingo6', models.ImageField(null=True, upload_to='bingo')),
                ('bingo7', models.ImageField(null=True, upload_to='bingo')),
                ('bingo8', models.ImageField(null=True, upload_to='bingo')),
                ('bingo9', models.ImageField(null=True, upload_to='bingo')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
