# Generated by Django 3.1.1 on 2020-09-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonomApp', '0002_remove_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_data',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
