# Generated by Django 3.1.1 on 2020-09-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonomApp', '0005_auto_20200925_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangkoker',
            name='bingo1',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo2',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo3',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo4',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo5',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo6',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo7',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo8',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
        migrations.AddField(
            model_name='bangkoker',
            name='bingo9',
            field=models.ImageField(null=True, upload_to='bingo'),
        ),
    ]
